### ISSUE TITLE
Provide option to set toJson options

### ISSUE THREAD

**Issue by chrisbateman** [FormidableLabs/webpack-stats-plugin#18]
When you generate stats with the Webpack CLI - it passes a particular set of "outputOptions" to `toJson()`. This results in different output than calling it without any options, which this plugin currently does.

Providing the ability to pass the custom outputOptions into the `toJson()` call would allow users to customize the results, or make them match the default Webpack results.

**Comment by ryan-roemer** [comment]
Hmm... Already you _could_ do something like:

```js
var StatsWriterPlugin = require("webpack-stats-plugin").StatsWriterPlugin;

module.exports = {
  plugins: [
    new StatsWriterPlugin({
      transform: function (data, opts) {
        var stats = opts.compiler.getStats().toJson(/* YOUR OPTIONS */)
        return DO_SOMETHING_WITH_CUSTOMIZED_STATS(stats);
      }
    })
  ]
};
```

to get you by, bypassing the `data` and using the compiler directly.

But, I would potentially be open to a PR with an additional options field to punch into the `toJson()` call. Feel free to strawman it here first!

**Comment by chrisbateman** [comment]
Shoot, I didn't notice that the transform function provides the compiler. So yeah, this could work:

```
new StatsWriterPlugin({
  transform: function(data, opts) {
    let stats = opts.compiler.getStats().toJson({chunkModules: true});
    return JSON.stringify(stats, null, 2); 
  }
});
```  

But it does require you to learn about `compiler.getStats().toJson()` and `JSON.stringify(stats, null, 2)` which this plugin covers for you otherwise.

An option to pass in the output options might look like this:
```
new StatsWriterPlugin({
  fields: null,
  stats: {chunkModules: true}
});
```

[Webpack's docs/config](https://webpack.js.org/configuration/stats/#stats) uses the property `stats` but internally it's called `outputOptions.` Either could work.

**Comment by chrisbateman** [comment]
Either way, thanks for the quick response!

**Comment by ryan-roemer** [comment]
Yeah, I'd be open to a PR that adds a field `stats` that is straight passed to `toJson()` with links to the documentation you linked in. Thanks!
