### ISSUE TITLE
Less package size using `files` in `package.json`

### ISSUE THREAD

**Issue by evilebottnawi** [FormidableLabs/webpack-stats-plugin#19]
Now in package there are a lot extra unnecessary files (`gulpfile.js`, `.jscsrc` and etc), be good not exported this in package.

**Comment by ryan-roemer** [comment]
Totally. I'd ❤️ a PR for this. (Or, I'll get to it eventually...)

**Comment by ryan-roemer** [comment]
Fixed in #21
