### ISSUE TITLE
Only one chunk in stats.json

### ISSUE THREAD

**Issue by manatarms** [FormidableLabs/webpack-stats-plugin#20]
I'm having some trouble using this plugin. My stats plugin by default looks like this
`{
  "assetsByChunkName": {
    "app": "app.js"
  }
}`

And I'm using this code to generate the file
`new StatsWriterPlugin({
    filename: 'stats.json' // Default
  })`

Any reason why it wouldn't show me all the information?
Thanks.

**Comment by ryan-roemer** [comment]
Yes, `assetsByChunkName` is the default value for `opts.fields` per the documentation: https://github.com/FormidableLabs/webpack-stats-plugin#statswriterpluginopts

You can see lots of examples of uses here: https://github.com/FormidableLabs/webpack-stats-plugin/blob/master/demo/webpack.config.js

And in your case, `fields: null,` sounds like the option you want.

**Comment by manatarms** [comment]
Thanks. I'll look into it. I'm closing this out for now. Cheers!
