### ISSUE TITLE
this.plugin('done')

### ISSUE THREAD

**Issue by sebastienbarre** [FormidableLabs/webpack-stats-plugin#3]
Can't it just be done with the plugin api?

```
  plugins: [
     // Everything else **first**.
    function() {
      this.plugin('done', function(stats) {
        require('fs').writeFileSync(
          './dist/assets.json',
          JSON.stringify(stats.toJson().assetsByChunkName));
      });
    }
  ],
```

**Comment by ryan-roemer** [comment]
@sebastienbarre -- If that's all you need, then you definitely should just DIY ;)

However, the plugin actually provides more than that as documented at: https://github.com/FormidableLabs/webpack-stats-plugin#statswriterpluginopts and does some useful things like `mkdir`-ing patches, etc...

**Comment by sebastienbarre** [comment]
Oh I see. Thanks. I was curious, no offense meant.

**Comment by ryan-roemer** [comment]
@sebastienbarre -- No worries! I originally started with something very close to what you had, then as I added more little options and had to implement it in a second project, I stopped and wrote this module. ;)
