### ISSUE TITLE
using stats file with dev server

### ISSUE THREAD

**Issue by davideapvd** [FormidableLabs/webpack-stats-plugin#37]
when using the dev server no stats.json file is output, how do I force it?

**Comment by ryan-roemer** [comment]
We wrote this plugin a long time ago for that exact scenario for _any_ asset in webpack (which is all in memory for the dev server): https://github.com/FormidableLabs/webpack-disk-plugin

That should fit your use case, although I'm not sure if it needs updating for modern webpack...

**Comment by fender** [comment]
@davideapvd I ended up writing my own plugin that is slightly simplified and always writes the stats JSON file to disk, regardless of whether you're in a dev or production environment.
https://github.com/fender/webpack-stats-disk-plugin

**Comment by davideapvd** [comment]
> @davideapvd I ended up writing my own plugin that is slightly simplified and always writes the stats JSON file to disk, regardless of whether you're in a dev or production environment.
> https://github.com/fender/webpack-stats-disk-plugin

thank you for this plugin, for now I ended up requesting the file from the dev server at the url http://devurl/stats.json, but if that will lead to some issue I'll trying your plugin.

**Comment by olessavluk** [comment]
WDS also have `writeToDisk` method which can help to achieve this https://github.com/webpack/webpack-dev-middleware#writetodisk
