### ISSUE TITLE
Feature request: way to generate filename dynamically

### ISSUE THREAD

**Issue by dominics** [FormidableLabs/webpack-stats-plugin#47]
I'm using this plugin within a build where I have a bunch of limitations outside of my control. The build is run by serverless-webpack, so it is controlling the Webpack configuration and running a bunch of parallel builds using cloned configuration, via https://github.com/serverless-heaven/serverless-webpack/blob/ffb1a5b0f027e8e40e9093075edc25db1b0e18d4/lib/validate.js#L212-L220 - I also want to make sure that my stats.json gets excluded from the final zip file that serverless-webpack produces.

One thing that would help me a lot would be if there was a way to transform not just the output contents, but also the filename the stats are output to. This would take the form of the `filename` option accepting a function that returns a string (in addition to the current just-a-string behavior) and calling it to resolve the final filename (perhaps with some useful arguments such as `curCompiler`)

**Comment by ryan-roemer** [comment]
I can take a look into the change later maybe this week. Easier path may just be a serverless package include/exclude ignore pattern (and I’ve done a lot of work with that stuff with the https://www.npmjs.com/package/serverless-jetpack#tracing-mode plugin that does what the webpack plugin does — trace imports — except using real files and not creating an extra bundle file).

Can you share some example file names you are seeking to exclude?

**Comment by ryan-roemer** [comment]
Oh, and happy to help separately if you want to try jetpack. It has things like built in multi-cpu concurrency too 🙂

**Comment by dominics** [comment]
Perhaps a bit off topic for webpack-stats-plugin, but it might help to explain a few things I tried, sure! 👍  You're probably aware of some of this stuff, because the jetpack README explains it by comparison (and jetpack does look quite nice, I'll definitely give it a look over!)

First approach was definitely to just try to exclude the `stats.json` from packaging, but:

- Because serverless-webpack does its own packaging, it doesn't take into account serverless' `package.exclude` at all AFAICT?
- It does have its own `custom.webpack.excludeFiles`, but that seems to only be used for [entrypoint resolution stuff](https://github.com/serverless-heaven/serverless-webpack/blob/ffb1a5b0f027e8e40e9093075edc25db1b0e18d4/lib/validate.js#L32), [not zipping unfortunately](https://github.com/serverless-heaven/serverless-webpack/blob/ffb1a5b0f027e8e40e9093075edc25db1b0e18d4/lib/packageModules.js#L34-L39) which is still just pulling in `**`

So, I ended up moving the stats out of the way with `filename: "../stats/stats.json"`, but then we get overwriting by the different parallel builds. So, my next approach was going to be `filename: () => `../stats/stats-${crypto.randomBytes(8).toString('hex')}.json` (or eventually naming the stats file after the entrypoint)

Probably, I should just be done with serverless-webpack, and that'll make my webpack-stats-plugin feature request go away 😉

**Comment by ryan-roemer** [comment]
Oh, haha, you are correct. (I forget because `serverless-jetpack` _does_ allow the built-in package.include|exclude in addition to tracing).

Let me review your use case in more depth and I'll check back in. All in all, the feature request isn't that big of a change I'm guessing, but we'll see if we can get you a first class solution without it.
