### ISSUE TITLE
Bug: webpack --watch adds "stats.json" to output causing "multiple assets emit different content to the same filename" error.

### ISSUE THREAD

**Issue by jdelStrother** [FormidableLabs/webpack-stats-plugin#59]
If I initialize the plugin with a custom `fields` list - eg:

```js
new StatsWriterPlugin({
    fields: ["assetsByChunkName", "assets", "entrypoints"],
  })
```

and run `webpack --watch`, each time assets are changed, I see this warning in the output:

```
WARNING in Conflict: Multiple assets emit different content to the same filename stats.json
```

This only started in the 1.0.x releases - 0.3.2 doesn't display the same problem.

There's a demo repo here: https://github.com/jdelStrother/webpack-stats-test

**Comment by ryan-roemer** [comment]
@jdelStrother Thanks for the repo! Issue confirmed.

The issue appears to be on the first build (or a standalone `webpack` run without `--watch`) we get this:

```js
{
  "assetsByChunkName": {
    "main": "main.js"
  },
  "assets": [
    {
      "name": "main.js",
      "size": 3892,
      "chunks": [
        "main"
      ],
      "chunkNames": [
        "main"
      ],
      "info": {},
      "emitted": false
    }
  ],
  "entrypoints": {
    "main": {
      "chunks": [
        "main"
      ],
      "assets": [
        "main.js"
      ],
      "children": {},
      "childAssets": {}
    }
  }
}
```

However, with `webpack --watch` in memory, it now picks up the "asset" of `stats.json` and adds _it_ to the stats output:

```js
{
  "assetsByChunkName": {
    "main": "main.js"
  },
  "assets": [
    {
      "name": "main.js",
      "size": 3892,
      "chunks": [
        "main"
      ],
      "chunkNames": [
        "main"
      ],
      "info": {},
      "emitted": true
    },
    {
      "name": "stats.json",
      "size": 435,
      "chunks": [],
      "chunkNames": [],
      "info": {},
      "emitted": false
    }
  ],
  "entrypoints": {
    "main": {
      "chunks": [
        "main"
      ],
      "assets": [
        "main.js"
      ],
      "children": {},
      "childAssets": {}
    }
  }
}
```

@evilebottnawi -- Any ideas on this issue?

Ideally I think that `stats.json` should not be considered part of the "stats" in play, so I can filter it out in the plugin itself before user-configured processing, but I want to make sure I don't inadvertently cause other issues...

**Comment by evilebottnawi** [comment]
@ryan-roemer weird, I can't reproduce

**Comment by evilebottnawi** [comment]
That's why we changed assets workflow, because most of them made just such a bug, logic is simple:
```js
if (curCompiler.emitAsset) {
  // New API
  const hasAsset = curCompiler.getAsset('stats.json');

  if (hasAsset) { 
    curCompiler.updateAsset(filename, source);
  } else {
    curCompiler.emitAsset(filename, source);
  }
} else {
   // Fallback to deprecated method.
    curCompiler.assets[filename] = source;
}
```

**Comment by evilebottnawi** [comment]
If you want we can implement cache here to avoid extra writing not changed assets
