### ISSUE TITLE
use webpack sources instead pseudo object

### ISSUE THREAD

**Issue by alexander-akait** [FormidableLabs/webpack-stats-plugin#65]
Ref: https://github.com/webpack-contrib/compression-webpack-plugin/issues/236

It is wrong to do this https://github.com/FormidableLabs/webpack-stats-plugin/blob/main/lib/stats-writer-plugin.js#L140 (maybe time to typescript or typescript jsdoc to avoid these problems in future).

It should be for webpack@5:
```js
const source = curCompiler.webpack 
  // webpack@5
  ? curCompiler.webpack.sources.RawSource(statsBuf) 
  // webpack@4
  : {
    source() {
      return statsBuf;
    },
    size() {
      return statsBuf.length;
    }
  }
```

**Comment by ryan-roemer** [comment]
Thanks! I’ll try and get a PR/release out sometime today...
